# Basic information.
title: The Solar Energy Association
description: The SEA is a student organization that advocates for solar energy and other forms of renewable energy. We fulfill the role of both activists and pioneers by being a hub of environmentalist activism and sustainable engineering.
baseurl: ""

# Contact information.
email: sea@ucmerced.edu
twitter: ucmsolarenergy
instagram: ucmsolarenergy
github: The-Solar-Energy-Association
